<?php
/**
 * Created by PhpStorm.
 * User: UnderTaker
 * Date: 23-Apr-20
 * Time: 9:21 PM
 */

class simpleClass
{
        public $username="";
        private $loggedin =false;

        public function login(){

            $this->loggedin= true;
        }
        public function logout(){
            $this->loggedin = true;
        }


}

class Administrator extends simpleClass{

    public function login()
    {
        parent::login(); // TODO: Change the autogenerated stub
        echo  $this->username." has just logged in";
    }


}


$member = new simpleClass();
$member->username="Maheeb";
$member->login();

$admin = new Administrator();
$admin->username ="Azmaeen";
$admin->login();





